version: 1

services:
  - type: web
    name: horarios-unt-app
    env: node
    plan: free
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
        sync: false
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        scope: build,runtime
        sync: false
      - key: NOMBRE_APLICACION
        value: Sistema de Horarios UNT
      - key: VERSION
        value: 1.0.0
